#ifndef MTYPES_H_INCLUDED
#define MTYPES_H_INCLUDED

#define START_DETECT_MTYPE 0x1
#define STOP_DETECT_MTYPE 0x2

#define PROXY_DETECT_TIMER_MTYPE 0x71
#define NIC_STATE_DETECT_TIMER_MTYPE 0x72

#define MAC_CHANGED_MTYPE 0x1E
#define IP_CHANGED_MTYPE 0x1F
#define MULTIPLE_ADAPTER_MTYPE 0x14
#define MULTIPLE_IP_MTYPE 0x15

#define STOP_PROXY_DETECT_TIMER_FLAG 0x1
#define STOP_NIC_STATE_DETECT_TIMER_FLAG 0x2

#define ADAPTER_UP_REPORT_MTYPE ADAPTER_UP
#define ADAPTER_DOWN_REPORT_MTYPE ADAPTER_DOWN
#define ADAPTER_DISABLE_REPORT_MTYPE ADAPTER_DISABLE
#define ADAPTER_ENABLE_REPORT_MTYPE ADAPTER_ENABLE
#define ADAPTER_ERROR_REPORT_MTYPE ADAPTER_ERROR

#define START_CONNECT_MTYPE 0x2711
#define STOP_CONNECT_MTYPE 0x2712
#define NOTIFY_UPGRADE_MTYPE 0xDD

#define ON_TRANSPACKET_MTYPE 0xD9

#define POST_DNS_QUERY_MTYPE 0x7DA
#define STOP_DNS_QUERY_MTYPE 0x7DB

#define SET_HELLOTIMER_PLEASE_MTYPE 0x82
#define CHANGE_HELLOPARA_MTYPE 0x7B

#define STOP_THREAD_MTYPE 0x456
#define START_THREAD_MTYPE 0x457
#define ON_TIMER_MTYPE 0x1E61

#define RECV_PAE_PACKET_MTYPE 0x6B

#define SEND_MESSAGE_MTYPE 0x7D2
#define CLOSE_ADAPTER_MTYPE 0x7D3

#define RECV_PACKET_RETURN_MTYPE 0x7D1
#define TIMER_CLEAR_DIR_SENDER 0x6F

#define ON_RECVPACKET_SAM_MTYPE 0x3E9
#define ON_INIT_SAM_MTYPE 0x3EA
#define ON_DEINIT_SAM_MTYPE 0x3EB
#define ON_RECVPACKET_SMP_MTYPE 0x3FC
#define ON_INIT_SMP_MTYPE 0x3FD
#define ON_DEINIT_SMP_MTYPE 0x3FE
#define ON_POST_SMP 0x460
#define ON_POST_SAM 0x461
#define ON_POST_NOREPONSE_SMP 0x462
#define ON_POST_NOREPONSE_SAM 0x463

#define SIMULATE_SU_LOGOFF_MTYPE 0xB0
#define FORCE_OFFLINE_MTYPE 0x8C

#endif // MTYPES_H_INCLUDED
