#ifndef MTYPES_H_INCLUDED
#define MTYPES_H_INCLUDED

#define START_DETECT_MTYPE 0x1
#define STOP_DETECT_MTYPE 0x2

#define ADAPTER_PROXY_DETECT_TIMER_MTYPE 0x71
#define NIC_STATE_DETECT_TIMER_MTYPE 0x72

#define MAC_CHANGED_MTYPE 0x1E
#define IP_CHANGED_MTYPE 0x1F
#define MULTIPLE_ADAPTER_MTYPE 0x14
#define MULTIPLE_IP_MTYPE 0x15

#define STOP_PROXY_DETECT_TIMER_FLAG 0x1
#define STOP_NIC_STATE_DETECT_TIMER_FLAG 0x2

#define ADAPTER_UP_REPORT_MTYPE ADAPTER_UP
#define ADAPTER_DOWN_REPORT_MTYPE ADAPTER_DOWN
#define ADAPTER_DISABLE_REPORT_MTYPE ADAPTER_DISABLE
#define ADAPTER_ENABLE_REPORT_MTYPE ADAPTER_ENABLE
#define ADAPTER_ERROR_REPORT_MTYPE ADAPTER_ERROR

#define START_CONNECT_MTYPE 0x2711
#define STOP_CONNECT_MTYPE 0x2712
#define NOTIFY_UPGRADE_MTYPE 0xDD

#define ON_TRANSPACKET_MTYPE 0xD9

#define POST_DNS_QUERY_MTYPE 0x7DA
#define STOP_DNS_QUERY_MTYPE 0x7DB

#define SET_HELLOTIMER_PLEASE_MTYPE 0x82
#define CHANGE_HELLOPARA_MTYPE 0x7B

#define STOP_THREAD_MTYPE 0x456
#define START_THREAD_MTYPE 0x457
#define ON_TIMER_MTYPE 0x1E61

#define RECV_PAE_PACKET_MTYPE 0x6B

#define SEND_MESSAGE_MTYPE 0x7D2
#define CLOSE_ADAPTER_MTYPE 0x7D3

#define RECV_PACKET_RETURN_MTYPE 0x7D1
#define TIMER_CLEAR_DIR_SENDER 0x6F

#define ON_RECVPACKET_SAM_MTYPE 0x3E9
#define ON_INIT_SAM_MTYPE 0x3EA
#define ON_DEINIT_SAM_MTYPE 0x3EB
#define ON_RECVPACKET_SMP_MTYPE 0x3FC
#define ON_INIT_SMP_MTYPE 0x3FD
#define ON_DEINIT_SMP_MTYPE 0x3FE
#define ON_POST_SMP 0x460
#define ON_POST_SAM 0x461
#define ON_POST_NOREPONSE_SMP 0x462
#define ON_POST_NOREPONSE_SAM 0x463

#define SIMULATE_SU_LOGOFF_MTYPE 0xB0
#define FORCE_OFFLINE_MTYPE 0x8C
#define WM_OTHER_WANT_LOGOFF 0x8D
#define LOGOFF_SOMEWHAT_MTYPE 0x7D
#define COMPATIBLE_LOGOFF_MTYPE 0xB8

#define PROCESS_CONNECT_MTYPE 0x1

#define HELLO_TIMER_MTYPE 0x70

#define HANDSHAKE_TO_SAM_MTYPE 0x69
#define ASK_SMP_INIT_DATA_MTYPE 0x6A
#define HANDSHAKE_TO_SMP_MTYPE 0x6B

#define ANNOUNCE_DHCP_RESULT_MTYPE 0xC6

#define DO_FORCE_OFFLINE_MTYPE 0x85 // anything to do with FORCE_OFFLINE_MTYPE ?
#define REAUTH_MTYPE 0x86
#define POST_ARP_ATTACK_PARAM_MTYPE 0xD7

#define RECEIVE_SEC_DOMAIN_MTYPE 0xB2

#define STOP_OCX_MTYPE 0xB9
#define GET_HI_RESULT_MTYPE 0xC4

#define PROXY_DETECT_TIMER_MTYPE 0xA

#define PACKET_NOTIFY_MTYPE 0x68
#define SAY_HELLO_MTYPE 0x7C

#define STATE_MOVE_MTYPE 0x4E35
#define START_STATE_MACHINE_MTYPE 0x4E36
#define CTRLTHREAD_START_STATE_MACHINE_MTYPE 0x4E37
#define SEND_LOGOFF_MTYPE 0x4E39

#define AUTH_WHILE_MTYPE 0x6C
#define START_WHILE_MTYPE 0x6D
#define HOLD_WHILE_MTYPE 0x6E

#define EAP_FAILURE_MTYPE 0xAA
#define HOLD_MTYPE 0xDFD

#define CONNECT_NOTIFY_MTYPE 0x6A
#define STATE_MACHINE_RETURN_MTYPE 0x69
#define PACKET_RETURN_MTYPE 0x6B
#define UPGRADE_RETURN_MTYPE 0x72
#define SAY_SA_EVENT_MTYPE 0x83
#define SHOW_SA_MSG_MTYPE 0x84
#define ADAPTER_STATE_MTYPE 0xDA
#define PATCH_LOGOFF_MTYPE 0xA2
#define RECEIVED_PROXY_DETECT_RESULT_MTYPE 0xDB
#define OPEN_SSO_URL_MTYPE 0xDC
#define RECONNECT_TIMER_MTYPE 0x66
#define OPEN_SSO_URL_TIMER_MTYPE 0x74
#define REAUTH_TIMER_MTYPE 0x73
#define DHCP_TIMEOUT_MTYPE 0x67
#define DHCP_IP_MTYPE 0x68

#endif // MTYPES_H_INCLUDED
