#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "gcc -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -DTERMIO -ggdb3 -Wall -DMD32_REG_T=int -DMD5_ASM"
  #define PLATFORM "debug-linux-x86_64"
  #define DATE "Sun Jul 20 13:21:28 CST 2025"
#endif
